import { useState, useEffect } from "react";
import type { AIInsight } from "@dementia/contracts";
import { api } from "../api";

interface Props {
  patientId: string;
  token: string;
  onBack: () => void;
}

const riskClass: Record<string, string> = {
  HIGH: "insight-high",
  MEDIUM: "insight-medium",
  LOW: "insight-low"
};

const riskIcon: Record<string, string> = {
  HIGH: "🔴",
  MEDIUM: "🟡",
  LOW: "🟢"
};

export function AIInsightsView({ patientId, token, onBack }: Props) {
  const [insights, setInsights] = useState<AIInsight[]>([]);
  const [loading, setLoading] = useState(true);
  const [expanded, setExpanded] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const loadInsights = () => {
    setLoading(true);
    setError(null);
    api.getInsights(patientId, token)
      .then(setInsights)
      .catch((e: Error) => setError(e.message || "We could not load insights. Please try again."))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    loadInsights();
  }, [patientId, token]);

  if (loading) return <div className="loading-inline"><div className="loading-spinner-sm" /> Loading insights...</div>;

  return (
    <div className="insights-view">
      <div className="view-header">
        <button className="btn-back" onClick={onBack}>← Overview</button>
        <h2>🧠 AI Insights</h2>
      </div>

      <p className="insights-disclaimer">
        ℹ️ These insights are generated from structured activity data. They are informational only and do not constitute medical advice.
      </p>

      {error && <div className="error-card" role="alert"><p>{error}</p><button type="button" className="btn btn-primary" onClick={loadInsights}>Retry</button></div>}

      {!error && insights.length === 0 ? (
        <div className="empty-state">
          <p>No insights generated yet. Check back after patient activity is recorded.</p>
        </div>
      ) : (
        <div className="insights-list">
          {insights.map(insight => (
            <div key={insight.id} className={`insight-card ${riskClass[insight.riskLevel] ?? ""}`}>
              <button
                type="button"
                className="insight-card-header"
                onClick={() => setExpanded(e => e === insight.id ? null : insight.id)}
                aria-expanded={expanded === insight.id}
              >
                <div className="insight-risk-badge">
                  {riskIcon[insight.riskLevel]} {insight.riskLevel} Risk
                </div>
                <div className="insight-summary">{insight.summary}</div>
                <div className="insight-timestamp">
                  {new Date(insight.createdAt).toLocaleString([], {
                    month: "short", day: "numeric",
                    hour: "2-digit", minute: "2-digit"
                  })}
                </div>
                <span className="expand-icon">{expanded === insight.id ? "▲" : "▼"}</span>
              </button>

              {expanded === insight.id && (
                <div className="insight-details">
                  <div className="insight-section">
                    <h4>Contributing Signals</h4>
                    <ul className="signal-list">
                      {insight.contributingSignals.map((s, i) => (
                        <li key={i}>{s}</li>
                      ))}
                    </ul>
                  </div>
                  <div className="insight-section">
                    <h4>💡 Recommended Action</h4>
                    <p className="recommended-action">{insight.recommendedAction}</p>
                  </div>
                  <div className="insight-section insight-provider">
                    Generated by: <code>{insight.provider}</code>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
